export const state = {
  currentFilter: "all",
  markers: {},
  moderatingFactors: {},
  moderatingFactorLayer: null,
  regionCoords: {},
  regionBoundaries: {},
  regionMarkers: [],
  regionBoundaryLayer: null,
  subregionCoords: {},
  subregionBoundaries: {},
  subregionMarkers: [],
  subregionBoundaryLayer: null,
  activeCountryKey: null,
  countriesData: null,
  quizQuestions: [],
  generatedQuestions: [],
  currentQuiz: null,
  quizScore: 0,
  quizCount: 0,
  quizTotal: 10,
  quizPool: [],
  quizMode: "all",
  lastCategory: null,
  weakAreas: {},
  studiedPages: JSON.parse(localStorage.getItem("wineStudiedPages") || "[]"),
  favorites: JSON.parse(localStorage.getItem("wineFavorites") || "[]"),
  progress: JSON.parse(localStorage.getItem("wineProgress") || JSON.stringify({
    quizzesPlayed: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
    weakAreas: {}
  })),
  dataCache: new Map()
};
